// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3dsGamesAPI.Data;

#nullable disable

namespace _3dsGamesAPI.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("_3dsGamesAPI.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CopiesSold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMultiplayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            CopiesSold = 6440000,
                            IsMultiplayer = false,
                            Publisher = "Nintendo",
                            ReleaseDate = new DateTime(2011, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Zelda: Ocarina of Time 3D"
                        },
                        new
                        {
                            GameId = 2,
                            CopiesSold = 400000,
                            IsMultiplayer = true,
                            Publisher = "Capcom",
                            ReleaseDate = new DateTime(2011, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Resident Evil: The Mercenaries 3D"
                        },
                        new
                        {
                            GameId = 3,
                            CopiesSold = 16760000,
                            IsMultiplayer = true,
                            Publisher = "Nintendo * The Pokemon Company",
                            ReleaseDate = new DateTime(2013, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pokémon X and Y"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
